package gui;
import java.awt.*;
import javax.swing.*;

public class Caramel extends JPanel{
	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -119351983683823414L;
	private static int numberCaramels;
	private Color myColor;

	public Caramel(int x, int y, int size) {
		numberCaramels++;
		setOpaque(false);
		setMyColor();
		setBounds(x,y,size,size);
	}
	protected void paintComponent(Graphics g){
		super.paintComponent(g);
		g.setColor(myColor);
		g.fillOval(0, 0, getWidth(), getHeight());
    }
	public void setMyColor(){
		int min = 0, max = 255,r,g,b;
		do{
			r = min+(int)(Math.random()*((max-min)+1));
			g = min+(int)(Math.random()*((max-min)+1));
			b = min+(int)(Math.random()*((max-min)+1));
		}while ((r<230 && g<230 && b<230) || (r>100 && g>100 && b>100));
		this.myColor = new Color(r,g,b);
	}
	public static int numberCaramels(){
		return numberCaramels;
	}
	public static void subtractNumberCaramels(){
		numberCaramels--;
	}
}
