package gui;
public class Floor extends GameObject {
	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -9176126706165708219L;
	private Caramel contains;
	Floor(int x, int y, int size) {
		super(x, y, false, false, size);
		setLayout(null);
		this.contains = new Caramel(size/3,size/3,size/3);
		setOpaque(false);
		add(this.contains);
	}
	public Object contains(){
		return this.contains;
	}
	public void empty(){
		Caramel.subtractNumberCaramels();
		remove(this.contains);
		this.contains = null;
		repaint();
	}
}
