package gui;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

public class Ghost extends MovableObject {
	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -9176126706165708219L;
	
	Ghost(int x, int y, int size) {
		super(x, y, true, true, size);
		setMyColor();
		setOpaque(false);
	}
	Ghost(Point point, int size) {
		super(point.x, point.y, true, true, size);
		setMyColor();
		setOpaque(false);
	}
	protected void paintComponent(Graphics g){
		super.paintComponent(g);
		g.setColor(myColor);
		g.fillOval(0, 0, getWidth(), getHeight());
		g.fillRect(1, getHeight()/2, getWidth()-1, getHeight()/2);
		g.setColor(Color.BLACK);
		g.fillOval(getWidth()/2-8, getHeight()/3, 7, 7);
		g.fillOval(getWidth()/2+1, getHeight()/3, 7, 7);
		g.fillOval(1, getHeight()-4, 8, 8);
		g.fillOval(11, getHeight()-4, 8, 8);
		g.fillOval(21, getHeight()-4, 8, 8);
    }
}
