package gui;
import java.awt.Point;

public class MovableObject extends GameObject {
	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = 1771378738432072034L;
	protected int direction=0;
	protected int speed;
	MovableObject(int x,int y, boolean occupied, boolean perceivedOccupied, int size) {
		super(x, y, true, true, size);
		setSpeed();
	}
	public void setSpeed(){
		this.speed = getWidth()/2;
	}
	public void move(Point point){
		this.point = point;
		this.origo.x = point.x+getWidth()/2;
		this.origo.y = point.y+getWidth()/2;
		setLocation(this.point);
	}
	public void moveDirection(int direction, int size){
		int x=0,y=0;
		this.direction=direction;
		switch(direction){
		case 0:
			x=-1;
			break;
		case 1:
			x=+1;
			break;
		case 2:
			y=+1;
			break;
		case 3:
			y=-1;
			break;
		}
		do{
			this.point.x += (size/speed)*x;
			this.point.y += (size/speed)*y;
		}while(this.point.x == size/2 && this.point.y == size/2);
		this.origo.x = point.x+getWidth()/2;
		this.origo.y = point.y+getWidth()/2;
		setLocation(this.point);
	}
}
