package gui;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

public class Player extends MovableObject {
	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -9176126706165708219L;
	private int count=0, mouthSize=3;
	Player(int x, int y, int size) {
		super(x, y, true, true, size);
		setOpaque(false);
		this.myColor = new Color(255,100,255);
	}
	Player(Point point, int size) {
		super(point.x, point.y, true, true, size);
		setOpaque(false);
		this.myColor = new Color(255,100,255);
	}
	public void eat(){
		this.count=10;
	}
	protected void paintComponent(Graphics g){
		super.paintComponent(g);
		g.setColor(myColor);
		g.fillOval(0, 0, getWidth(), getHeight());
		g.setColor(Color.BLACK);
		count--;
		
		if(count>0)
			mouthSize = 10;
		else if (count<=0){
			mouthSize = 3;
		}
		switch(direction){
		case 0:
			g.fillPolygon(new int[]{getWidth()/4,0,0}, new int[]{getHeight()/2,getHeight()/2-mouthSize,getHeight()/2+mouthSize}, 3);
			break;
		case 1:
			g.fillPolygon(new int[]{getWidth()*3/4,getWidth(),getWidth()}, new int[]{getHeight()/2,getHeight()/2-mouthSize,getHeight()/2+mouthSize}, 3);
			break;
		case 2:
			g.fillPolygon(new int[]{getWidth()/2,getWidth()/2-mouthSize,getWidth()/2+mouthSize}, new int[]{getHeight()*3/4,getHeight(),getHeight()}, 3);
			break;
		case 3:
			g.fillPolygon(new int[]{getWidth()/2,getWidth()/2-mouthSize,getWidth()/2+mouthSize}, new int[]{getHeight()/4,0,0}, 3);
			break;
		}
    }
}
